### ISSUE TITLE
Option to not show progress

### ISSUE THREAD

**Issue by drq883** [gesquive/fast-cli#2]
Please add some option, maybe --simple, to not show any progress but just the estimated download speed. I want to use this for a nagios service test and only want the final estimate. 

Thanks.

**Comment by drq883** [comment]
I added the code to my forked copy and created pull request #3

**Comment by gesquive** [comment]
Thanks for the PR.

The code changes are in the repo if you want to build it yourself. At the moment, I am trying to figure out some traviscl deployment issues. Once I figure that out the binaries should be under releases.
